### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by jenminemp** [dezmoanded/vrn-torch-to-keras#1]
Traceback (most recent call last):
  File "vrn_torch_to_keras.py", line 159, in <module>
    model = model(t)
  File "vrn_torch_to_keras.py", line 123, in model
    l = add_conv(64, get(t, 3), l)
  File "vrn_torch_to_keras.py", line 54, in add_conv
    conv131(input_dim, l,tobj=get(tobj, 1), first_layer=True),
  File "vrn_torch_to_keras.py", line 28, in conv131
    tbn1 = get(tobj, 0)
  File "vrn_torch_to_keras.py", line 24, in get
    tout, _ = getr(tobj, ln)
  File "vrn_torch_to_keras.py", line 12, in getr
    for module in tobj['modules']:
TypeError: 'NoneType' object is not iterable

**Comment by jenminemp** [comment]
> Traceback (most recent call last):
> File "vrn_torch_to_keras.py", line 159, in
> model = model(t)
> File "vrn_torch_to_keras.py", line 123, in model
> l = add_conv(64, get(t, 3), l)
> File "vrn_torch_to_keras.py", line 54, in add_conv
> conv131(input_dim, l,tobj=get(tobj, 1), first_layer=True),
> File "vrn_torch_to_keras.py", line 28, in conv131
> tbn1 = get(tobj, 0)
> File "vrn_torch_to_keras.py", line 24, in get
> tout, _ = getr(tobj, ln)
> File "vrn_torch_to_keras.py", line 12, in getr
> for module in tobj['modules']:
> TypeError: 'NoneType' object is not iterable

**Comment by jsmwoolf** [comment]
@jenminemp,

As a heads up, I just created a repository that converts this neural network to Tensorflow 2.0.  You can find it [here](https://github.com/jsmwoolf/vrn-torch7-to-tf2).
